s =  input("Enter time in seconds : ")
s = float (s)
#print(s)
h = float (int (s/3600))
#print(h)
m = float (int ((s-(h*3600))/60))
#print(m)
sec = s - (h*3600) - (m*60)
#print(sec)
print ("Your time is "+ str(int(h)) + " hours " + str(int(m)) + " minutes and " + str(int(sec)) + " seconds")
